<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Division;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class UserAdminController extends Controller
{
    public function index()
    {
        $q        = request('q', '');
        $division = request('division_id');

        $users = User::query()
            ->with('division')
            ->when($q, function ($qrb) use ($q) {
                $qrb->where(function ($w) use ($q) {
                    $w->where('name', 'like', "%{$q}%")
                      ->orWhere('email', 'like', "%{$q}%");
                });
            })
            ->when($division, fn($qrb) => $qrb->where('division_id', $division))
            ->orderBy('name')
            ->paginate(20)
            ->withQueryString();

        $divisions = Division::orderBy('name')->get();

        return view('admin.users.index', compact('users', 'divisions', 'q', 'division'));
    }

    // optional (kalau pakai tombol Tambah User)
    public function create()
    {
        $divisions = Division::orderBy('name')->get();
        return view('admin.users.create', compact('divisions'));
    }

    // optional (kalau pakai tombol Tambah User)
    public function store(Request $r): RedirectResponse
    {
        $data = $r->validate([
            'name'        => ['required','string','max:150'],
            'email'       => ['required','email','max:190','unique:users,email'],
            'division_id' => ['nullable','uuid','exists:divisions,id'],
            'role'        => ['nullable','string','max:50'],
        ]);

        $pwdPlain = Str::password(12);

        $user = User::create([
            'name'        => $data['name'],
            'email'       => $data['email'],
            'division_id' => $data['division_id'] ?? null,
            'role'        => $data['role'] ?? null,
            'password'    => Hash::make($pwdPlain),
        ]);

        return redirect()->route('admin.users.edit', $user)->with([
            'generated_password' => $pwdPlain, // tampil sekali
        ]);
    }

    public function edit(User $user)
    {
        $divisions = Division::orderBy('name')->get();
        return view('admin.users.edit', compact('user', 'divisions'));
    }

    public function updateDivision(Request $request, User $user): RedirectResponse
    {
        $data = $request->validate([
            'division_id' => ['nullable','uuid', Rule::exists('divisions','id')],
        ]);

        $before = [
            'division_id'   => $user->getOriginal('division_id'),
            'division_name' => optional($user->division)->name,
        ];

        $user->update(['division_id' => $data['division_id'] ?? null]);
        $user->load('division');

        $after = [
            'division_id'   => $user->division_id,
            'division_name' => optional($user->division)->name,
        ];

        if (function_exists('audit')) {
            audit('user.update_division', [
                'target_user_id'   => $user->id,
                'target_user_name' => $user->name,
                'before'           => $before,
                'after'            => $after,
            ], User::class, $user->id);
        }

        return back()->with('status','Division updated.');
    }

    /** Reset password: auto-generate, simpan hash, tampilkan plaintext sekali via flash */
    public function resetPassword(User $user): RedirectResponse
    {
        $newPassword = Str::password(14);

        $user->forceFill(['password' => Hash::make($newPassword)])->save();

        if (function_exists('audit')) {
            audit('user.reset_password_generated', [
                'target_user_id'    => $user->id,
                'target_user_email' => $user->email,
                'by_user_id'        => auth()->id(),
                'note'              => 'Password regenerated by admin. Plaintext not stored.',
            ], User::class, $user->id);
        }

        // kirim satu flash saja biar tidak dobel alert
        return back()->with('generated_password', $newPassword);
    }

    public function destroy(User $user): RedirectResponse
    {
        // pengaman opsional
        if ($user->id === auth()->id()) {
            return back()->with('status', 'Tidak boleh menghapus akun sendiri.');
        }

        $user->delete(); // soft delete; ganti ->forceDelete() untuk hard delete

        if (function_exists('audit')) {
            audit('user.delete', [
                'target_user_id'    => $user->id,
                'target_user_email' => $user->email,
                'by_user_id'        => auth()->id(),
            ], User::class, $user->id);
        }

        return redirect()->route('admin.users.index')->with('status', 'User berhasil dihapus.');
    }
}
